var Base = require("../base.js");
var C = require("./../interface/constants.js");

var initAnonymousOperator = require("../operator/operator.js").initAnonymousOperator;

var shaderConstant = {};
shaderConstant[C.SHADER_CONSTANT_KEY.OBJECT_ID] = "objectID";
shaderConstant[C.SHADER_CONSTANT_KEY.SCREEN_TRANSFORM] = "screenTransform";
shaderConstant[C.SHADER_CONSTANT_KEY.SCREEN_TRANSFORM_NORMAL] = "screenTransformNormal";
shaderConstant[C.SHADER_CONSTANT_KEY.VIEW_TRANSFORM] = "viewTransform";
shaderConstant[C.SHADER_CONSTANT_KEY.VIEW_TRANSFORM_NORMAL] = "viewTransformNormal";
shaderConstant[C.SHADER_CONSTANT_KEY.WORLD_TRANSFORM] = "worldTransform";
shaderConstant[C.SHADER_CONSTANT_KEY.WORLD_TRANSFORM_NORMAL] = "worldTransformNormal";

var setShaderConstant = function(type, name){
    shaderConstant[type] = name;
};


/**
 * The output configuration of a VertexShader generated by Xflow
 * @constructor
 */
var VSConfig = function(){
    this._attributes = {};
    this._blockedNames = [];
    this._addInput = {};
    this._addOutput = {};
    this._codeFragments = [];
    this._outputChanneling = {};
};

VSConfig.prototype.addAttribute = function(type, name, optional){
    if(this._attributes[name]){
        if(this._attributes[name].type != type)
            throw new Error("Tries to add two attributes with different types of name '" + name + '"');
        this._attributes[name].optional = this._attributes[name].optional && optional;
        return;
    }
    this._attributes[name] = {type: type, optional: optional, channeling: []};
};

VSConfig.prototype.channelAttribute = function(inputName, outputName, code){
    this._attributes[inputName].channeling.push( { outputName : outputName, code : code });
};

VSConfig.prototype.addInputParameter = function(type, name, uniform){
    if(this._addInput[name])
        return;
    this._addInput[name] = { type: type, uniform: uniform };
    this._blockedNames.push(name);
};
VSConfig.prototype.addOutputParameter = function(type, name){
    if(this._addOutput[name])
        return;
    this._addOutput[name] = { type: type };
    this._blockedNames.push(name);
};
VSConfig.prototype.addCodeFragment = function(codeFragment){
    this._codeFragments.push(codeFragment);
};

VSConfig.prototype.addBlockedName = function(name){
    this._blockedNames.push(name);
};

VSConfig.prototype.getBlockedNames = function(){
    return this._blockedNames;
};

VSConfig.prototype.getFilter = function(){
    return Object.keys(this._attributes);
};
VSConfig.prototype.getKey = function(){
    var key = "";
    for(var name in this._attributes){
        var attr = this._attributes[name];
        key += ";" + attr.type + "," + name + "," + attr.optional;
    }
    return key;
};

var c_vs_operator_cache = {};

VSConfig.prototype.getOperator = function(){
    var key = this.getKey();
    if(c_vs_operator_cache[key])
        return c_vs_operator_cache[key];

    var outputs = [], params = [], glslCode = "\t// VS Connector\n";
    var name = "VSConnect";
    for(var attributeName in this._attributes){
        var attr = this._attributes[attributeName];
        var type = C.getTypeName(attr.type);
        outputs.push( { type: type, name: attributeName} );
        params.push( { type: type, source: attributeName, optional: attr.optional} );
        name += "T" + type + "N" + attributeName + "O" + attr.optional + ".";
    }
    var operator = initAnonymousOperator(name,
    {
        outputs: outputs,
        params:  params,
        evaluate_glsl: glslCode
    });
    c_vs_operator_cache[key] = operator;
    return operator;
};

var VertexShader = function(programData){
    this._programData = programData;
    this._glslCode = null;
    this._inputNames = [];
    this._outputNames = [];
    this._inputInfo = {};
    this._outputInfo = {};
};

Object.defineProperty(VertexShader.prototype, "inputNames", {
    set: function(v){
        throw new Error("inputNames is readonly");
    },
    get: function(){ return this._inputNames; }
});

Object.defineProperty(VertexShader.prototype, "outputNames", {
    set: function(v){
        throw new Error("outputNames is readonly");
    },
    get: function(){ return this._outputNames; }
});

VertexShader.prototype.isInputUniform = function(name){
    return this._inputInfo[name].uniform;
};
VertexShader.prototype.getInputData = function(name){
    return this._programData.getDataEntry(this._inputInfo[name].index);
};

VertexShader.prototype.isOutputNull = function(name){
    return this._outputInfo[name].iteration == C.ITERATION_TYPE.NULL;
};
VertexShader.prototype.isOutputFragmentUniform = function(name){
    return this._outputInfo[name].iteration == C.ITERATION_TYPE.ONE;
};
VertexShader.prototype.getUniformOutputData = function(name){
    return this._programData.getDataEntry(this._outputInfo[name].index);
};
VertexShader.prototype.getOutputType = function(name){
    return this._outputInfo[name].type;
};
VertexShader.prototype.getOutputSourceName = function(name){
    return this._outputInfo[name].sourceName;
};
VertexShader.prototype.getGLSLCode = function(){
    return this._glslCode;
};

module.exports = {
    shaderConstant: shaderConstant,
    setShaderConstant: setShaderConstant,
    VSConfig: VSConfig,
    VertexShader: VertexShader
};
